Repository ProjectFRIDAY/Plan-Dial-Renewal, pull requests merged in 2022-05, with the labels that each got.

#1 다이얼 구조 추가
  ios/Runner.xcodeproj/project.pbxproj
  lib/TimeTable.dart
  lib/main.dart
  lib/models/dial.dart
  lib/models/dial_manager.dart
  lib/models/time.dart
  lib/models/week_schedule.dart
  lib/screens/Add_Dial.dart
  lib/screens/Check_List.dart
  lib/screens/main.dart
  lib/screens/select_page.dart
  lib/screens/time_table.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: 분류: 기능 추가 / 개선, 상태: 리뷰 진행 중, 우선 순위: 높음

#3 다이얼 - Appointment 연동 함수 추가
  lib/models/dial.dart
  lib/models/dial_manager.dart
  lib/models/schedule.dart
  lib/models/week_schedule.dart
  test/dial_managing_test.dart
Labels: 분류: 기능 추가 / 개선, 상태: 리뷰 진행 중, 우선 순위: 긴급

#12 feat: Icon change and change Tab bar height
  ios/Podfile.lock
  lib/screens/main.dart
Labels: 분류: 기능 추가 / 개선, 상태: 처리 필요, 우선 순위: 낮음

#16 Feature/dial animation
  lib/screens/main.dart
Labels: 분류: 기능 추가 / 개선, 상태: 리뷰 진행 중, 우선 순위: 중간

#17 체크 리스트 완성
  lib/models/dial.dart
  lib/screens/Check_List.dart
  lib/utils/db_manager.dart
Labels: 분류: 기능 추가 / 개선, 상태: 처리 필요, 우선 순위: 높음

#18 Feature/dial list
  lib/models/dial.dart
  lib/models/dial_manager.dart
  lib/screens/Add_Dial.dart
  lib/screens/main.dart
  pubspec.lock
  pubspec.yaml
Labels: 분류: 기능 추가 / 개선, 분류: 비정상적인 기능, 상태: 완료, 우선 순위: 높음

#19 Feature/dial animation
  ios/Podfile.lock
  lib/screens/main.dart
Labels: 분류: 기능 추가 / 개선, 상태: 처리 필요, 우선 순위: 높음

#21 메인 페이지에 다이얼 추가 버튼 추가
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/screens/Add_Dial.dart
  lib/screens/main.dart
Labels: 분류: 기능 추가 / 개선, 상태: 완료, 우선 순위: 긴급

#24 경영 피드백 수정 (시간 표기법, selectTime 시간표시, disable을 알람 아이콘 변경)
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/TodayList.dart
  lib/screens/Add_Dial.dart
  lib/screens/main.dart
  lib/screens/select_page.dart
Labels: 분류: 기능 추가 / 개선, 상태: 처리 필요, 우선 순위: 긴급

#25 Feature/advance
  android/app/build.gradle
  lib/screens/Add_Dial.dart
  lib/screens/main.dart
  lib/screens/select_page.dart
  lib/screens/time_table.dart
  lib/utils/noti_manager.dart
  pubspec.lock
  pubspec.yaml
Labels: 분류: 기능 추가 / 개선, 상태: 처리 필요, 우선 순위: 긴급
